### PR TITLE
Updated ratatui to avoid mismatch (fixes #35)

### LINKED ISSUE #35: `cargo install jwt-ui` fails
**Describe the bug**
Fresh `cargo install jwt-ui` fails with build errors.

Log
```
error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jwt-ui-1.1.0/src/ui/encoder.rs:133:5
     |
132  |     textarea.set_block(
     |              --------- arguments to this method are incorrect
133  | /     Block::default()
134  | |       .borders(Borders::ALL)
135  | |       .style(get_input_style(&text_input.input_mode, light_theme)),
     | |__________________________________________________________________^ expected `ratatui::widgets::block::Block<'_>`, found `ratatui::widgets::Block<'_>`
     |
     = note: `ratatui::widgets::Block<'_>` and `ratatui::widgets::block::Block<'_>` have similar names, but are actually distinct types
note: `ratatui::widgets::Block<'_>` is defined in crate `ratatui`
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.25.0/src/widgets/block.rs:233:1
     |
233  | pub struct Block<'a> {
     | ^^^^^^^^^^^^^^^^^^^^
note: `ratatui::widgets::block::Block<'_>` is defined in crate `ratatui`
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.2/src/widgets/block.rs:64:1
     |
64   | pub struct Block<'a> {
     | ^^^^^^^^^^^^^^^^^^^^
     = note: perhaps two different versions of crate `ratatui` are being used?
note: method defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui-textarea-0.4.0/src/textarea.rs:1648:12
```
**To Reproduce**
Steps to reproduce the behavior or a screencast
1. cargo install jwt-ui

**Expected behavior**
I expect it installs `jwt-ui` properly with no errors.

**Desktop (please complete the following information):**
 - WSL2
 - Windows Terminal
 - bash, rustc 1.77.2, rustup 1.27.0
 - jwt-ui version: 1.1.0

### PR DESCRIPTION
**Pull request by tolik518**
This pr should fix #35.

The compile error in #35 is thrown due to a ratatui version mismatch. Some code had to be adjusted for the new version, but these were only minor changes

Also Im think its good to keep the libraries up to date :)

### CODE REVIEW

**Comment by tolik518** [comment]
Additionally, I had to swap the multi-byte checkmark icon with a single-byte checkmark icon since it was breaking tests. Also it could break the UI since it's rendered differently on different systems

**Comment by deepu105** [comment]
Thank you.  I'll check and merge

**Comment by deepu105** [comment]
Thank you @tolik518 , Any reason you changed the icons for tick and cross? now they are not that obvious

**Comment by tolik518** [comment]
Hey @deepu105, yes, they were multi byte symbols, which means that they get rendered differently depending on which font, shell and or terminal you use.  
Futhermore a test was failing for me with the old icons which I could have fixed with some hacks, but that would make the tests more obscure and I don't think that would have been good practice

**Comment by deepu105** [comment]
Ya seems like something changed at ratatui. I'll keep the ones you proposed for now

**Pull request merged**
